[package]

name = "um"
version = "0.0.1"
authors = ["Colin Davidson <colrdavidson@gmail.com>"]

#[dependencies.phf]
#git = "https://github.com/sfackler/rust-phf"

#[dependencies.phf_mac]
#git = "https://github.com/sfackler/rust-phf"
